from crewai import Task
from agents import interface_agent, sql_agent, alerts_agent, analysis_agent

# 1. SQL Query Task (SQL Agent)
sql_query_task = Task(
    description=(
        "1. Inspect the database schema of 'inventory.db' using the schema tool.\n"
        "2. Query the entire list of products including category, stock levels, reorder thresholds, and expiry dates.\n"
        "3. Query the historical sales data from 'sales_history' for all products, specifically noting "
        "any changes in quantities sold during normal days vs. Ramadan (is_ramadan = 1)."
    ),
    expected_output=(
        "A structured markdown compilation of the retrieved products table and sales history data, "
        "showing baseline daily sales vs. Ramadan seasonal sales for each item."
    ),
    agent=sql_agent
)

# 2. Alert Generation Task (Alerts Agent)
alerts_task = Task(
    description=(
        "1. Retrieve the simulated current system date using the get_system_date tool.\n"
        "2. Analyze the products retrieved in the previous task.\n"
        "3. Identify and flag any product where: \n"
        "   - The current stock_level is less than or equal to its reorder_threshold (Low Stock).\n"
        "   - The expiry_date is within 3 days of the simulated current date (Near Expiry).\n"
        "4. Create a clean list of these active alerts with the product name, category, and reason for the alert."
    ),
    expected_output=(
        "A markdown table listing all active alerts, categorized by 'Low Stock' and 'Near Expiry', "
        "detailing current stock levels, thresholds, and days remaining until expiry."
    ),
    agent=alerts_agent,
    context=[sql_query_task]
)

# 3. Demand Forecasting & Recommendation Task (Analysis Agent)
analysis_task = Task(
    description=(
        "1. Analyze the list of active alerts (from the Alerts Agent) and the sales history (from the SQL Agent).\n"
        "2. For each low stock item, calculate a recommended reorder quantity. Notice from the sales history "
        "if a product exhibits a major demand spike during Ramadan (e.g., Dates and Arabic Pita Bread). If it does, "
        "recommend a larger restock quantity (e.g., 2x to 3x the standard replenishment amount) to avoid stockouts during "
        "upcoming holiday seasons.\n"
        "3. For each near expiry item, suggest a strategy: should we mark it down (e.g., 50% discount on Pita Bread "
        "expiring in 2 days) to clear stock, or should we skip restocking for now if sales velocity is low?\n"
        "4. Provide solid business and operational reasoning for every replenishment recommendation, localized to UAE retail habits."
    ),
    expected_output=(
        "A detailed replenishment analysis with specific recommended order quantities, markdowns, and "
        "the operational reasoning behind each decision."
    ),
    agent=analysis_agent,
    context=[sql_query_task, alerts_task]
)

# 4. Interface Consolidation Task (Interface Agent / Manager)
interface_task = Task(
    description=(
        "1. Read the staff query: '{query}'\n"
        "2. Review the data, alerts, and recommendations generated by the team.\n"
        "3. Consolidate and format this information into a premium, executive-ready Markdown Dashboard.\n"
        "The report must include:\n"
        "   - A striking Executive Summary (focused on Automatix UAE store operations).\n"
        "   - A 'Critical Inventory Alerts' section (low stock & near-expiry products).\n"
        "   - A 'Replenishment Action Plan' containing suggested order quantities, markdown suggestions, "
        "and detailed operational justifications.\n"
        "Use rich formatting, lists, tables, and clear emoji headers to make the dashboard look highly professional."
    ),
    expected_output="A beautiful, complete, and formatted Markdown report representing the operations dashboard.",
    agent=interface_agent,
    context=[sql_query_task, alerts_task, analysis_task]
)
